"""图谱契约数据 —— 自动生成，请勿手工编辑。

来源：profiles/graph_contract.yaml
生成：python3 scripts/gen_graph_contract.py --write
校验：tests/test_35_graph_contract.py 断言本文件与来源一致（--check）

改契约请改 profiles/graph_contract.yaml 然后重新生成。
直接改本文件会在下一次 --check 时被测试打回。
"""

CONTRACT_VERSION = 1

TIMESTAMP_FIELD = 'last_seen'

# 历史遗留的时间戳字段名。读取侧要兼容，写入侧只写 TIMESTAMP_FIELD。
TIMESTAMP_LEGACY_ALIASES = ('last_updated', 'last_scanned')

SOURCES = frozenset(['aws-etl', 'business-layer', 'cfn-etl', 'deepflow-dns', 'deepflow-etl', 'deepflow-l4', 'manual-fix', 'nfm', 'xray'])

# 写一次属性：边上这些属性只由**首个发现者**写入，后续任何源都不得覆盖。
# source 记录的是谁首先发现了这条依赖 —— 被覆盖等于抹掉发现史。
EDGE_WRITE_ONCE_ATTRS = frozenset(['dependency_kind', 'first_seen', 'source'])

# 节点属性的权威来源。列表外的来源不得覆盖该属性。
NODE_ATTR_AUTHORITY = {   'Microservice': {   'az': ['aws-etl'],
                        'fault_boundary': ['aws-etl'],
                        'recovery_priority': ['aws-etl', 'business-layer']}}

NODE_TYPES = {   'AWSServiceEndpoint': {   'identity': 'name',
                              'immutable': True,
                              'note': '归一化后的服务名（ssm 与 SimpleSystemsManagement 已归一）'},
    'AvailabilityZone': {'identity': 'name', 'immutable': True, 'note': 'az name，AWS 侧不可变'},
    'BusinessCapability': {   'identity': 'name',
                              'immutable': True,
                              'note': '业务声明，来自 business_config.json'},
    'ChaosExperiment': {'identity': 'experiment_id', 'immutable': True, 'writer': 'chaos'},
    'Database': {'identity': 'name', 'immutable': True, 'note': '逻辑库名'},
    'Deployment': {   'identity': 'name',
                      'immutable': 'lifetime',
                      'scope_note': '未按 namespace 限定'},
    'DynamoDBTable': {'identity': 'name', 'immutable': True, 'preferred': 'arn'},
    'EC2Instance': {   'identity': 'instance_id',
                       'immutable': True,
                       'note': 'name 取自 Name 标签，已于 2026-08-29 改以 instance_id 为身份'},
    'ECRRepository': {'identity': 'name', 'immutable': True, 'preferred': 'arn'},
    'EKSCluster': {'identity': 'name', 'immutable': True},
    'HPA': {'identity': 'name', 'immutable': 'lifetime', 'scope_note': '未按 namespace 限定'},
    'Incident': {'identity': 'id', 'immutable': True, 'writer': 'rca_window_flush'},
    'K8sService': {   'identity': 'name',
                      'immutable': 'lifetime',
                      'scope_note': '未按 namespace 限定'},
    'LambdaFunction': {'identity': 'name', 'immutable': True, 'preferred': 'arn'},
    'ListenerRule': {   'identity': 'name',
                        'immutable': True,
                        'note': 'name 传入的就是 rule_arn（handler.py:273）'},
    'LoadBalancer': {   'identity': 'name',
                        'immutable': True,
                        'note': 'ALB 创建后不可改名；dict 里已有 arn，可升级',
                        'preferred': 'arn'},
    'Microservice': {   'identity': 'name',
                        'immutable': True,
                        'note': '规范服务名，来自 service_mappings.json，是声明而非观测值'},
    'Namespace': {   'identity': 'name',
                     'immutable': True,
                     'scope_note': '未按 cluster 限定；多集群场景同名 namespace 会碰撞'},
    'NeptuneCluster': {'identity': 'name', 'immutable': True},
    'NeptuneInstance': {'identity': 'name', 'immutable': True},
    'Pod': {   'identity': 'name',
               'immutable': 'lifetime',
               'scope_note': '未按 namespace 限定；Pod 重建即换名，属预期'},
    'RDSCluster': {'identity': 'name', 'immutable': True, 'note': 'DBClusterIdentifier'},
    'RDSInstance': {'identity': 'name', 'immutable': True, 'note': 'DBInstanceIdentifier'},
    'Region': {'identity': 'name', 'immutable': True, 'note': 'region code，AWS 侧不可变'},
    'S3Bucket': {'identity': 'name', 'immutable': True, 'note': '桶名全局唯一且不可变'},
    'SNSTopic': {'identity': 'name', 'immutable': True, 'preferred': 'arn'},
    'SQSQueue': {'identity': 'name', 'immutable': True, 'preferred': 'arn'},
    'SecurityGroup': {   'identity': 'sg_id',
                         'immutable': True,
                         'note': 'GroupName 创建后不可改，但 sg_id 更稳且已在 dict 里'},
    'StepFunction': {'identity': 'name', 'immutable': True, 'preferred': 'arn'},
    'Subnet': {   'identity': 'subnet_id',
                  'immutable': True,
                  'note': 'name 取自 Name 标签（collectors/ec2.py:56）是可变的，必须以 subnet_id 为身份'},
    'TargetGroup': {   'identity': 'name',
                       'immutable': True,
                       'note': 'TargetGroupName 在 AWS 侧创建后不可改，所以 name 是合法身份键。arn '
                               '更稳（跨账号/区域唯一），但**切换需要先回填** —— 2026-08-30 活图谱审计：18 个现存 '
                               'TargetGroup 节点全部没有 arn 属性，直接切会在首轮 ETL 造 18 个重复节点。现已把 arn '
                               '作为普通属性写入（此前图谱里根本没有该字段），待存量都带上 arn 后可用 '
                               'infra/migrate_identity_keys.py 复核再切',
                       'preferred': 'arn'},
    'TopologyChange': {   'identity': 'change_id',
                          'immutable': True,
                          'note': '追加式事件日志，稳态可 0 实例',
                          'writer': 'etl_deepflow'},
    'VPC': {   'identity': 'vpc_id',
               'immutable': True,
               'note': "name 取自 Name 标签（collectors/ec2.py:76 tags.get('Name', "
                       "v['VpcId'])）是可变的，必须以 vpc_id 为身份"}}

EDGE_TYPES = {   'AccessesData': {   'dependency': True,
                        'dst': [   'AWSServiceEndpoint',
                                   'DynamoDBTable',
                                   'LambdaFunction',
                                   'NeptuneCluster',
                                   'RDSCluster',
                                   'RDSInstance',
                                   'S3Bucket',
                                   'StepFunction'],
                        'expires_seconds': 21600,
                        'note': '四个源都写（aws/cfn 静态，deepflow 动态，xray 补度量）；取最长源窗口 = xray 的 '
                                '6h，否则会误杀 xray 发现的边',
                        'pairs': [   ['LambdaFunction', 'AWSServiceEndpoint'],
                                     ['LambdaFunction', 'DynamoDBTable'],
                                     ['LambdaFunction', 'LambdaFunction'],
                                     ['LambdaFunction', 'NeptuneCluster'],
                                     ['LambdaFunction', 'RDSCluster'],
                                     ['LambdaFunction', 'S3Bucket'],
                                     ['Microservice', 'AWSServiceEndpoint'],
                                     ['Microservice', 'DynamoDBTable'],
                                     ['Microservice', 'RDSCluster'],
                                     ['Microservice', 'RDSInstance'],
                                     ['Microservice', 'S3Bucket'],
                                     ['Microservice', 'StepFunction'],
                                     ['StepFunction', 'LambdaFunction']],
                        'src': ['LambdaFunction', 'Microservice', 'StepFunction']},
    'AffectedService': {   'dependency': False,
                           'dst': ['Microservice'],
                           'expires_seconds': None,
                           'pairs': [['Incident', 'Microservice']],
                           'src': ['Incident']},
    'BelongsTo': {   'dependency': False,
                     'dst': ['EKSCluster', 'K8sService', 'NeptuneCluster', 'RDSCluster'],
                     'expires_seconds': None,
                     'pairs': [   ['Database', 'RDSCluster'],
                                  ['EC2Instance', 'EKSCluster'],
                                  ['Namespace', 'EKSCluster'],
                                  ['NeptuneInstance', 'NeptuneCluster'],
                                  ['Pod', 'K8sService'],
                                  ['RDSInstance', 'RDSCluster']],
                     'src': [   'Database',
                                'EC2Instance',
                                'Namespace',
                                'NeptuneInstance',
                                'Pod',
                                'RDSInstance']},
    'Calls': {   'dependency': True,
                 'dst': ['LambdaFunction', 'Microservice'],
                 'expires_seconds': 1800,
                 'note': '唯一写入源是 deepflow，阈值同 CALLS_INACTIVE_AFTER_SECONDS',
                 'pairs': [   ['LambdaFunction', 'LambdaFunction'],
                              ['Microservice', 'Microservice']],
                 'retention_seconds': 604800,
                 'src': ['LambdaFunction', 'Microservice']},
    'ConnectsTo': {   'dependency': False,
                      'dst': ['Database'],
                      'expires_seconds': None,
                      'pairs': [['Microservice', 'Database']],
                      'src': ['Microservice']},
    'Contains': {   'dependency': False,
                    'dst': ['AvailabilityZone'],
                    'expires_seconds': None,
                    'pairs': [['Region', 'AvailabilityZone']],
                    'src': ['Region']},
    'DependsOn': {   'dependency': True,
                     'dst': ['ECRRepository', 'RDSCluster', 'SNSTopic', 'SQSQueue'],
                     'expires_seconds': 21600,
                     'note': 'aws + cfn 静态 + deepflow 动态',
                     'pairs': [   ['BusinessCapability', 'RDSCluster'],
                                  ['BusinessCapability', 'SNSTopic'],
                                  ['BusinessCapability', 'SQSQueue'],
                                  ['Microservice', 'ECRRepository'],
                                  ['Microservice', 'SQSQueue']],
                     'src': ['BusinessCapability', 'Microservice']},
    'ForwardsTo': {   'dependency': False,
                      'dst': ['Microservice', 'TargetGroup'],
                      'expires_seconds': None,
                      'pairs': [   ['ListenerRule', 'TargetGroup'],
                                   ['LoadBalancer', 'TargetGroup'],
                                   ['TargetGroup', 'Microservice']],
                      'src': ['ListenerRule', 'LoadBalancer', 'TargetGroup']},
    'HasRule': {   'dependency': False,
                   'dst': ['ListenerRule'],
                   'expires_seconds': None,
                   'pairs': [['LoadBalancer', 'ListenerRule']],
                   'src': ['LoadBalancer']},
    'HasSG': {   'dependency': False,
                 'dst': ['SecurityGroup'],
                 'expires_seconds': None,
                 'pairs': [   ['EC2Instance', 'SecurityGroup'],
                              ['EKSCluster', 'SecurityGroup'],
                              ['LoadBalancer', 'SecurityGroup'],
                              ['NeptuneCluster', 'SecurityGroup'],
                              ['RDSCluster', 'SecurityGroup']],
                 'src': [   'EC2Instance',
                            'EKSCluster',
                            'LoadBalancer',
                            'NeptuneCluster',
                            'RDSCluster']},
    'Implements': {   'dependency': False,
                      'dst': ['BusinessCapability', 'LambdaFunction', 'Microservice'],
                      'expires_seconds': None,
                      'pairs': [   ['K8sService', 'LambdaFunction'],
                                   ['K8sService', 'Microservice'],
                                   ['LambdaFunction', 'BusinessCapability'],
                                   ['Microservice', 'BusinessCapability']],
                      'src': ['K8sService', 'LambdaFunction', 'Microservice']},
    'Invokes': {   'dependency': False,
                   'dst': ['LambdaFunction'],
                   'expires_seconds': None,
                   'pairs': [   ['LambdaFunction', 'LambdaFunction'],
                                ['SNSTopic', 'LambdaFunction'],
                                ['StepFunction', 'LambdaFunction']],
                   'src': ['LambdaFunction', 'SNSTopic', 'StepFunction']},
    'InvokesVia': {   'dependency': False,
                      'dst': ['StepFunction'],
                      'expires_seconds': 21600,
                      'note': '受 drift 对账覆盖',
                      'pairs': [['Microservice', 'StepFunction']],
                      'src': ['Microservice']},
    'Involves': {   'dependency': False,
                    'dst': ['Microservice'],
                    'expires_seconds': None,
                    'pairs': [['Incident', 'Microservice']],
                    'src': ['Incident']},
    'LocatedIn': {   'dependency': False,
                     'dst': ['AvailabilityZone', 'EKSCluster', 'Region', 'Subnet', 'VPC'],
                     'expires_seconds': None,
                     'pairs': [   ['AWSServiceEndpoint', 'Region'],
                                  ['EC2Instance', 'AvailabilityZone'],
                                  ['EC2Instance', 'Subnet'],
                                  ['ECRRepository', 'Region'],
                                  ['EKSCluster', 'Region'],
                                  ['LoadBalancer', 'AvailabilityZone'],
                                  ['Microservice', 'EKSCluster'],
                                  ['NeptuneCluster', 'Region'],
                                  ['NeptuneInstance', 'AvailabilityZone'],
                                  ['Pod', 'AvailabilityZone'],
                                  ['RDSCluster', 'Region'],
                                  ['RDSInstance', 'AvailabilityZone'],
                                  ['S3Bucket', 'Region'],
                                  ['SNSTopic', 'Region'],
                                  ['SQSQueue', 'Region'],
                                  ['Subnet', 'AvailabilityZone'],
                                  ['Subnet', 'VPC'],
                                  ['VPC', 'Region']],
                     'src': [   'AWSServiceEndpoint',
                                'EC2Instance',
                                'ECRRepository',
                                'EKSCluster',
                                'LoadBalancer',
                                'Microservice',
                                'NeptuneCluster',
                                'NeptuneInstance',
                                'Pod',
                                'RDSCluster',
                                'RDSInstance',
                                'S3Bucket',
                                'SNSTopic',
                                'SQSQueue',
                                'Subnet',
                                'VPC']},
    'Manages': {   'dependency': False,
                   'dst': ['Deployment', 'Microservice', 'Pod'],
                   'expires_seconds': None,
                   'pairs': [   ['Deployment', 'Microservice'],
                                ['Deployment', 'Pod'],
                                ['HPA', 'Deployment']],
                   'src': ['Deployment', 'HPA']},
    'MentionsResource': {   'dependency': False,
                            'dst': ['EC2Instance', 'Microservice'],
                            'expires_seconds': None,
                            'pairs': [   ['Incident', 'EC2Instance'],
                                         ['Incident', 'Microservice']],
                            'src': ['Incident']},
    'OwnedBy': {   'dependency': False,
                   'dst': ['Namespace'],
                   'expires_seconds': None,
                   'pairs': [['Microservice', 'Namespace']],
                   'src': ['Microservice']},
    'ProtectsAccess': {   'dependency': False,
                          'dst': ['LambdaFunction'],
                          'expires_seconds': None,
                          'pairs': [['SecurityGroup', 'LambdaFunction']],
                          'src': ['SecurityGroup']},
    'PublishesTo': {   'dependency': False,
                       'dst': ['SNSTopic', 'SQSQueue'],
                       'expires_seconds': 21600,
                       'note': '受 drift 对账覆盖',
                       'pairs': [['Microservice', 'SNSTopic'], ['Microservice', 'SQSQueue']],
                       'src': ['Microservice']},
    'Routes': {   'dependency': False,
                  'dst': ['Pod'],
                  'expires_seconds': None,
                  'pairs': [['K8sService', 'Pod']],
                  'src': ['K8sService']},
    'RoutesTo': {   'dependency': False,
                    'dst': ['TargetGroup'],
                    'expires_seconds': None,
                    'pairs': [['LoadBalancer', 'TargetGroup']],
                    'src': ['LoadBalancer']},
    'RunsOn': {   'dependency': False,
                  'dst': ['EC2Instance', 'Pod'],
                  'expires_seconds': None,
                  'pairs': [['Microservice', 'Pod'], ['Pod', 'EC2Instance']],
                  'src': ['Microservice', 'Pod']},
    'TestedBy': {   'dependency': False,
                    'dst': ['ChaosExperiment'],
                    'expires_seconds': None,
                    'pairs': [['Microservice', 'ChaosExperiment']],
                    'src': ['Microservice']},
    'TriggeredBy': {   'dependency': False,
                       'dst': ['LambdaFunction', 'Microservice'],
                       'expires_seconds': None,
                       'pairs': [['Incident', 'Microservice'], ['SQSQueue', 'LambdaFunction']],
                       'src': ['Incident', 'SQSQueue']},
    'WritesTo': {   'dependency': False,
                    'dst': ['NeptuneCluster', 'S3Bucket', 'SNSTopic', 'SQSQueue'],
                    'expires_seconds': None,
                    'pairs': [   ['LambdaFunction', 'NeptuneCluster'],
                                 ['Microservice', 'S3Bucket'],
                                 ['Microservice', 'SNSTopic'],
                                 ['Microservice', 'SQSQueue']],
                    'src': ['LambdaFunction', 'Microservice']}}
